const traverseDOM = function(){
  let body = document.querySelector('body');
  let div1Array = body.children;
  let div1 = div1Array[0];
  div1.style.width = "400px";
  div1.style.height = "400px";
  div1.style.background = "black";
  div1.style.margin = "0px auto";
  div1.style.paddingTop = "50px";
  div1.style.boxSizing = "border-box";
  let div2Array = div1.children;
  let div2 =div2Array[0];
  div2.style.width = "300px";
  div2.style.height = "300px";
  div2.style.background = "green";
  div2.style.margin = "0px auto";
  div2.style.paddingTop = "70px";
  div2.style.boxSizing = "border-box";
  let lastChild = div2.lastElementChild;
  lastChild.style.width = "100px";
  lastChild.style.height = "100px";
  lastChild.style.background = "yellow";
  lastChild.style.margin = "0px auto";
  let nextSibling = lastChild.previousElementSibling;
  nextSibling.style.width = "100px";
  nextSibling.style.height = "100px";
  nextSibling.style.background = "red";
  nextSibling.style.margin = "0px auto";
  div2.appendChild(lastChild);
  div1.appendChild(div2);
  body.appendChild(div1);
}();

traverseDOM();
